In [ ]:
print("hello")

hello


In [ ]:
!nvidia-smi

Thu Mar 19 06:35:23 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


print(torch.__version__)

2.9.0+cu126


In [ ]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
matrix = torch.tensor([[7 , 1] , [2 , 2]])
print(matrix)

tensor([[7, 1],
        [2, 2]])


In [ ]:
matrix[0][0]
matrix.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],[2,3,4],[3,6,7]]])

In [ ]:
rand_tensor = torch.rand([2,3 , 3])
rand_tensor

tensor([[[0.3071, 0.3921, 0.7295],
         [0.2686, 0.1175, 0.2718],
         [0.6032, 0.3066, 0.9668]],

        [[0.8794, 0.4163, 0.3285],
         [0.5729, 0.1077, 0.7840],
         [0.3198, 0.9961, 0.9507]]])

In [ ]:
colorchannels = torch.rand(size=(224 , 224 , 4 ))
colorchannels

tensor([[[0.3504, 0.8625, 0.3794, 0.0665],
         [0.9133, 0.1519, 0.5692, 0.2771],
         [0.4242, 0.0875, 0.3195, 0.7580],
         ...,
         [0.5600, 0.7980, 0.7899, 0.2887],
         [0.5439, 0.9313, 0.1031, 0.5825],
         [0.0076, 0.1517, 0.5383, 0.3330]],

        [[0.2525, 0.3193, 0.0128, 0.7839],
         [0.8726, 0.2478, 0.6772, 0.0734],
         [0.4015, 0.0078, 0.4982, 0.9972],
         ...,
         [0.6642, 0.4644, 0.2391, 0.8109],
         [0.2701, 0.0446, 0.3412, 0.7507],
         [0.4397, 0.8701, 0.1309, 0.1724]],

        [[0.7480, 0.9175, 0.9770, 0.4350],
         [0.1590, 0.5134, 0.1911, 0.5130],
         [0.1817, 0.2173, 0.8067, 0.7150],
         ...,
         [0.8917, 0.5644, 0.4697, 0.4321],
         [0.2112, 0.0411, 0.3335, 0.5186],
         [0.4722, 0.6318, 0.9836, 0.3266]],

        ...,

        [[0.0137, 0.5260, 0.5748, 0.6473],
         [0.3134, 0.8167, 0.0356, 0.5383],
         [0.1641, 0.4203, 0.4602, 0.9383],
         ...,
         [0.4732, 0.8

In [ ]:
zeros = torch.zeros([2,3])

In [ ]:
ones = torch.ones([2,23])
ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1.]])

In [ ]:
x = torch.arange(1, 11)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
  xy = torch.rand([2 , 3]);
  xy = torch.tensor(xy , dtype=None , requires_grad=False)
  xy

/tmp/ipython-input-831869688.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  xy = torch.tensor(xy , dtype=None , requires_grad=False)


tensor([[0.8862, 0.8513, 0.1329],
        [0.9738, 0.0754, 0.6700]])

In [ ]:
# min max , aggregation etc ,,

In [ ]:
test2=torch.rand(7)
test2

tensor([0.6828, 0.0372, 0.9888, 0.3647, 0.7707, 0.5825, 0.6463])

In [ ]:
print(max(test2) , min(test2)  , test2.dtype)


tensor(0.9888) tensor(0.0372) torch.float32


In [ ]:

torch.mean(test2.type(torch.float16))

tensor(0.5820, dtype=torch.float16)

In [ ]:
test3 = torch.rand(19)
test3.shape

torch.Size([19])

In [ ]:
test3=test3.reshape(19,1)
test3

tensor([[0.8033],
        [0.2030],
        [0.5593],
        [0.4505],
        [0.1229],
        [0.9584],
        [0.8920],
        [0.7467],
        [0.0920],
        [0.9039],
        [0.3614],
        [0.2400],
        [0.0289],
        [0.5460],
        [0.1635],
        [0.4579],
        [0.6252],
        [0.1137],
        [0.4929]])

In [ ]:
test3[:0]=5
test3

tensor([[0.8033],
        [0.2030],
        [0.5593],
        [0.4505],
        [0.1229],
        [0.9584],
        [0.8920],
        [0.7467],
        [0.0920],
        [0.9039],
        [0.3614],
        [0.2400],
        [0.0289],
        [0.5460],
        [0.1635],
        [0.4579],
        [0.6252],
        [0.1137],
        [0.4929]])

In [ ]:
test4=torch.rand(4,3)
test4
test4 = test4.squeeze()
test4

tensor([[0.4920, 0.5441, 0.7813],
        [0.6327, 0.4100, 0.2663],
        [0.4307, 0.8228, 0.5211],
        [0.6160, 0.4591, 0.6135]])

In [ ]:
tensor_with_one_dim = torch.rand(1, 5, 1, 3)
print(f"Original tensor: {tensor_with_one_dim}\n")
print(f"Original shape: {tensor_with_one_dim.shape}\n")

squeezed_tensor = tensor_with_one_dim.squeeze()
print(f"Squeezed tensor: {squeezed_tensor}\n")
print(f"Squeezed shape: {squeezed_tensor.shape}")

Original tensor: tensor([[[[0.0151, 0.2634, 0.5706]],

         [[0.2586, 0.1066, 0.2452]],

         [[0.1906, 0.2422, 0.9973]],

         [[0.2107, 0.8483, 0.8963]],

         [[0.8675, 0.3251, 0.7461]]]])

Original shape: torch.Size([1, 5, 1, 3])

Squeezed tensor: tensor([[0.0151, 0.2634, 0.5706],
        [0.2586, 0.1066, 0.2452],
        [0.1906, 0.2422, 0.9973],
        [0.2107, 0.8483, 0.8963],
        [0.8675, 0.3251, 0.7461]])

Squeezed shape: torch.Size([5, 3])


In [ ]:
y=torch.rand(3)
y=y.unsqueeze(dim=0)
y.shape

torch.Size([1, 3])

In [ ]:
# indexing
import torch
x=torch.rand(1,9).reshape(1 , 3 , 3)
x


tensor([[[0.8992, 0.6292, 0.3135],
         [0.1753, 0.4277, 0.5050],
         [0.3266, 0.9731, 0.5175]]])

In [ ]:
random_seed = 41
torch.manual_seed(random_seed)

x=torch.rand(3,4)

torch.manual_seed(random_seed)
y=torch.rand(3,4)
x
y
print(x==y)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


As you can see, `squeeze()` removed the dimensions of size 1 at position 0 and 2, changing the shape from `(1, 5, 1, 3)` to `(5, 3)`.